framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    #esi: true
    #fragments: true
    php_errors:
        log: true
    session:
        handler_id: null
        cookie_secure: true
        cookie_samesite: 'none'
        storage_factory_id: session.storage.factory.native
