bitbag_shopware_app_system:
  resource: '@BitBagShopwareAppSystemBundle/Resources/config/routes.yaml'

create_package:
  methods: ['POST']
  path: /app/create-package
  controller: BitBag\ShopwareDpdApp\Controller\CreatePackageController::create

get_label:
  methods: ['POST']
  path: /app/get-label
  controller: BitBag\ShopwareDpdApp\Controller\LabelController::getLabel

show_label:
  methods: ['GET']
  path: /app/show-label
  controller: BitBag\ShopwareDpdApp\Controller\LabelController::showLabel

configuration_module_show:
  methods: ['GET', 'POST']
  path: /app/modules/configuration
  controller: bitbag.shopware_dpd_app.controller.configuration_module
