registration:
  methods: ['GET']
  path: /app/registration
  controller: bitbag.shopware_dpd_app.app_system.controller.registration_controller

confirm_registration:
  methods: ['POST']
  path: /app/registration/confirm
  controller: bitbag.shopware_skeleton_app.app_system.controller.confirmation_controller

app_lifecycle:
  resource: './lifecycle_routes.yaml'
  prefix: /app/lifecycle
  methods: ['POST']
  name_prefix: app_lifecycle_

get_order:
  methods: ['POST']
  path: /app/send-order
  controller: bitbag.shopware_skeleton_app.controller.order
