bitbag_shopware_app_system:
  resource: '@BitBagShopwareAppSystemBundle/Resources/config/routes.yaml'

create_package:
  methods: ['POST']
  path: /app/create-package
  controller: BitBag\ShopwareDpdApp\Controller\CreatePackageController::create

get_label:
  methods: ['POST']
  path: /app/get-label
  controller: BitBag\ShopwareDpdApp\Controller\LabelController::getLabel

show_label:
  methods: ['GET']
  path: /app/show-label
  controller: BitBag\ShopwareDpdApp\Controller\LabelController::showLabel

get_protocol:
  methods: ['POST']
  path: /app/get-protocol
  controller: BitBag\ShopwareDpdApp\Controller\ProtocolController::getProtocol

show_protocol:
  methods: ['GET']
  path: /app/show-protocol
  controller: BitBag\ShopwareDpdApp\Controller\ProtocolController::showProtocol

configuration_module_index:
  methods: ['GET', 'POST']
  path: /app/module/configuration
  controller: BitBag\ShopwareDpdApp\Controller\ConfigurationModuleController::index

configuration_module_api_data_sales_channel:
  methods: ['GET']
  path: /app/module/sales-channel-inputs
  controller: BitBag\ShopwareDpdApp\Controller\ConfigurationModuleController::getApiDataBySalesChannel

api_data_check_credentials:
  methods: ['POST']
  path: /app/module/api-check-credentials
  controller: BitBag\ShopwareDpdApp\Controller\ApiCredentialsController::checkCredentials
