bitbag_shopware_app_system:
  resource: '@BitBagShopwareAppSystemBundle/Resources/config/routes.yaml'

create_package:
  methods: ['POST']
  path: /app/create-package
  controller: BitBag\ShopwareDpdApp\Controller\CreatePackageController::create

configuration_module_show:
  methods: ['GET', 'POST']
  path: /app/modules/configuration
  controller: bitbag.shopware_dpd_app.controller.configuration_module
