bitbag_shopware_app_system:
  resource: '@BitBagShopwareAppSystemBundle/Resources/config/routes.yaml'

get_order:
  methods: ['POST']
  path: /app/send-order
  controller: bitbag.shopware_skeleton_app.controller.order

configuration_module_show:
  methods: ['GET', 'POST']
  path: /app/modules/configuration
  controller: bitbag.shopware_dpd_app.controller.configuration_module
